name: Deploy to Shared Hosting

on:
  push:
    branches:
      - main # Change this to the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Change this to your PHP version

      - name: Install from composer.lock
        run: composer install --no-scripts --no-interaction

      - name: Copy .env file
        run: cp .env.example .env

      - name: Run Database Migrations
        run: php artisan migrate --force --seed

      - name: Create Deploy Directory
        run: mkdir deploy

      - name: Move deployment script to deploy dir
        run: mv ./deploy.php ./deploy/deploy.txt

      # - name: Build Zip
      #   run: tar --exclude='.deploy/' -czf deploy/project.tar.gz ./*

      # - name: Split Zip Into 9Mb Multiples
      #   run: split -b 9M deploy/project.tar.gz deploy/project.tar.gz.part

      - name: Test
        run: ls -lha deploy

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./deploy/
          server-dir: /deploy/

      # - name: Make HTTP Request to deploy.php
      #   run: curl "${{ secrets.DEPLOY_URL }}/deploy/deploy.php"
